repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  # Python linters
  - repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
      - id: black
  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
      - id: seed-isort-config
  - repo: https://github.com/timothycrosley/isort
    rev: 4.3.21
    hooks:
      - id: isort
  - repo: https://gitlab.com/pycqa/flake8
    rev: "3.8.3" # pick a git hash / tag to point to
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.782" # Use the sha / tag you want to point at
    hooks:
      - id: mypy

  # Node/TS Linters
  - repo: https://github.com/prettier/prettier
    rev: "2.1.1" # Use the sha or tag you want to point at
    hooks:
      - id: prettier
        language_version: 14.8.0

  - repo: https://github.com/pre-commit/mirrors-eslint
    files: \.[jt]sx?$ # *.js, *.jsx, *.ts and *.tsx
    rev: v7.8.1 # Use the sha / tag you want to point at
    hooks:
      - id: eslint
        language_version: 14.8.0
