version: "3.3"

services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile

    ports:
      - "3000:3000"
    env_file: frontend/.env
    stdin_open: true
    volumes:
      - ./frontend/src/:/usr/app/src

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file: backend/.env
    volumes:
      - ./backend/app/:/usr/app/app
      - ./backend/requirements.txt:/usr/app/requirements.txt
