// tslint:disable
/**
 * Mapt
 * Shape file uploader/sharing application
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as globalImportUrl from "url";
import { Configuration } from "./configuration";
import globalAxios, { AxiosInstance, AxiosPromise } from "axios";
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, BaseAPI, RequestArgs, RequiredError } from "./base";

/**
 *
 * @export
 * @interface Attribute
 */
export interface Attribute {
  /**
   *
   * @type {string}
   * @memberof Attribute
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof Attribute
   */
  display: string;
  /**
   *
   * @type {string}
   * @memberof Attribute
   */
  type: string;
}
/**
 *
 * @export
 * @interface BodyUploadShapeDatasetsShapefilePost
 */
export interface BodyUploadShapeDatasetsShapefilePost {
  /**
   *
   * @type {any}
   * @memberof BodyUploadShapeDatasetsShapefilePost
   */
  shape_file: any;
}
/**
 *
 * @export
 * @interface Dataset
 */
export interface Dataset {
  /**
   *
   * @type {string}
   * @memberof Dataset
   */
  label: string;
  /**
   *
   * @type {string}
   * @memberof Dataset
   */
  description: string;
  /**
   *
   * @type {Array<Attribute>}
   * @memberof Dataset
   */
  schema: Array<Attribute>;
}
/**
 *
 * @export
 * @interface HTTPValidationError
 */
export interface HTTPValidationError {
  /**
   *
   * @type {Array<ValidationError>}
   * @memberof HTTPValidationError
   */
  detail?: Array<ValidationError>;
}
/**
 *
 * @export
 * @interface Layer
 */
export interface Layer {
  /**
   *
   * @type {number}
   * @memberof Layer
   */
  id: number;
  /**
   *
   * @type {string}
   * @memberof Layer
   */
  label: string;
  /**
   *
   * @type {string}
   * @memberof Layer
   */
  group: string;
}
/**
 *
 * @export
 * @interface ValidationError
 */
export interface ValidationError {
  /**
   *
   * @type {Array<string>}
   * @memberof ValidationError
   */
  loc: Array<string>;
  /**
   *
   * @type {string}
   * @memberof ValidationError
   */
  msg: string;
  /**
   *
   * @type {string}
   * @memberof ValidationError
   */
  type: string;
}

/**
 * DefaultApi - axios parameter creator
 * @export
 */
export const DefaultApiAxiosParamCreator = function (
  configuration?: Configuration
) {
  return {
    /**
     *
     * @summary Get All Datasets
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getAllDatasetsDatasetsGet: async (
      options: any = {}
    ): Promise<RequestArgs> => {
      const localVarPath = `/datasets/`;
      const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }
      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarUrlObj.query = {
        ...localVarUrlObj.query,
        ...localVarQueryParameter,
        ...options.query,
      };
      // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
      delete localVarUrlObj.search;
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: globalImportUrl.format(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Get Dataset
     * @param {number} datasetId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getDatasetDatasetsDatasetIdGet: async (
      datasetId: number,
      options: any = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'datasetId' is not null or undefined
      if (datasetId === null || datasetId === undefined) {
        throw new RequiredError(
          "datasetId",
          "Required parameter datasetId was null or undefined when calling getDatasetDatasetsDatasetIdGet."
        );
      }
      const localVarPath = `/datasets/{dataset_id}`.replace(
        `{${"dataset_id"}}`,
        encodeURIComponent(String(datasetId))
      );
      const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }
      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarUrlObj.query = {
        ...localVarUrlObj.query,
        ...localVarQueryParameter,
        ...options.query,
      };
      // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
      delete localVarUrlObj.search;
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: globalImportUrl.format(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Get Layers
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getLayersLayersGet: async (options: any = {}): Promise<RequestArgs> => {
      const localVarPath = `/layers/`;
      const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }
      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarUrlObj.query = {
        ...localVarUrlObj.query,
        ...localVarQueryParameter,
        ...options.query,
      };
      // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
      delete localVarUrlObj.search;
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: globalImportUrl.format(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Upload a new shape file  This will eventually be offloaded to the ARQ worker but keep it simple for now and do it synchronously
     * @summary Upload Shape
     * @param {any} shapeFile
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    uploadShapeDatasetsShapefilePost: async (
      shapeFile: any,
      options: any = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'shapeFile' is not null or undefined
      if (shapeFile === null || shapeFile === undefined) {
        throw new RequiredError(
          "shapeFile",
          "Required parameter shapeFile was null or undefined when calling uploadShapeDatasetsShapefilePost."
        );
      }
      const localVarPath = `/datasets/shapefile/`;
      const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }
      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;
      const localVarFormParams = new FormData();

      if (shapeFile !== undefined) {
        localVarFormParams.append("shape_file", shapeFile as any);
      }

      localVarHeaderParameter["Content-Type"] = "multipart/form-data";

      localVarUrlObj.query = {
        ...localVarUrlObj.query,
        ...localVarQueryParameter,
        ...options.query,
      };
      // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
      delete localVarUrlObj.search;
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = localVarFormParams;

      return {
        url: globalImportUrl.format(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function (configuration?: Configuration) {
  return {
    /**
     *
     * @summary Get All Datasets
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getAllDatasetsDatasetsGet(
      options?: any
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Dataset>>
    > {
      const localVarAxiosArgs = await DefaultApiAxiosParamCreator(
        configuration
      ).getAllDatasetsDatasetsGet(options);
      return (
        axios: AxiosInstance = globalAxios,
        basePath: string = BASE_PATH
      ) => {
        const axiosRequestArgs = {
          ...localVarAxiosArgs.options,
          url: basePath + localVarAxiosArgs.url,
        };
        return axios.request(axiosRequestArgs);
      };
    },
    /**
     *
     * @summary Get Dataset
     * @param {number} datasetId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getDatasetDatasetsDatasetIdGet(
      datasetId: number,
      options?: any
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<Dataset>
    > {
      const localVarAxiosArgs = await DefaultApiAxiosParamCreator(
        configuration
      ).getDatasetDatasetsDatasetIdGet(datasetId, options);
      return (
        axios: AxiosInstance = globalAxios,
        basePath: string = BASE_PATH
      ) => {
        const axiosRequestArgs = {
          ...localVarAxiosArgs.options,
          url: basePath + localVarAxiosArgs.url,
        };
        return axios.request(axiosRequestArgs);
      };
    },
    /**
     *
     * @summary Get Layers
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getLayersLayersGet(
      options?: any
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Layer>>
    > {
      const localVarAxiosArgs = await DefaultApiAxiosParamCreator(
        configuration
      ).getLayersLayersGet(options);
      return (
        axios: AxiosInstance = globalAxios,
        basePath: string = BASE_PATH
      ) => {
        const axiosRequestArgs = {
          ...localVarAxiosArgs.options,
          url: basePath + localVarAxiosArgs.url,
        };
        return axios.request(axiosRequestArgs);
      };
    },
    /**
     * Upload a new shape file  This will eventually be offloaded to the ARQ worker but keep it simple for now and do it synchronously
     * @summary Upload Shape
     * @param {any} shapeFile
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async uploadShapeDatasetsShapefilePost(
      shapeFile: any,
      options?: any
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<Dataset>
    > {
      const localVarAxiosArgs = await DefaultApiAxiosParamCreator(
        configuration
      ).uploadShapeDatasetsShapefilePost(shapeFile, options);
      return (
        axios: AxiosInstance = globalAxios,
        basePath: string = BASE_PATH
      ) => {
        const axiosRequestArgs = {
          ...localVarAxiosArgs.options,
          url: basePath + localVarAxiosArgs.url,
        };
        return axios.request(axiosRequestArgs);
      };
    },
  };
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance
) {
  return {
    /**
     *
     * @summary Get All Datasets
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getAllDatasetsDatasetsGet(options?: any): AxiosPromise<Array<Dataset>> {
      return DefaultApiFp(configuration)
        .getAllDatasetsDatasetsGet(options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary Get Dataset
     * @param {number} datasetId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getDatasetDatasetsDatasetIdGet(
      datasetId: number,
      options?: any
    ): AxiosPromise<Dataset> {
      return DefaultApiFp(configuration)
        .getDatasetDatasetsDatasetIdGet(datasetId, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary Get Layers
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getLayersLayersGet(options?: any): AxiosPromise<Array<Layer>> {
      return DefaultApiFp(configuration)
        .getLayersLayersGet(options)
        .then((request) => request(axios, basePath));
    },
    /**
     * Upload a new shape file  This will eventually be offloaded to the ARQ worker but keep it simple for now and do it synchronously
     * @summary Upload Shape
     * @param {any} shapeFile
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    uploadShapeDatasetsShapefilePost(
      shapeFile: any,
      options?: any
    ): AxiosPromise<Dataset> {
      return DefaultApiFp(configuration)
        .uploadShapeDatasetsShapefilePost(shapeFile, options)
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI {
  /**
   *
   * @summary Get All Datasets
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof DefaultApi
   */
  public getAllDatasetsDatasetsGet(options?: any) {
    return DefaultApiFp(this.configuration)
      .getAllDatasetsDatasetsGet(options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Get Dataset
   * @param {number} datasetId
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof DefaultApi
   */
  public getDatasetDatasetsDatasetIdGet(datasetId: number, options?: any) {
    return DefaultApiFp(this.configuration)
      .getDatasetDatasetsDatasetIdGet(datasetId, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Get Layers
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof DefaultApi
   */
  public getLayersLayersGet(options?: any) {
    return DefaultApiFp(this.configuration)
      .getLayersLayersGet(options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Upload a new shape file  This will eventually be offloaded to the ARQ worker but keep it simple for now and do it synchronously
   * @summary Upload Shape
   * @param {any} shapeFile
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof DefaultApi
   */
  public uploadShapeDatasetsShapefilePost(shapeFile: any, options?: any) {
    return DefaultApiFp(this.configuration)
      .uploadShapeDatasetsShapefilePost(shapeFile, options)
      .then((request) => request(this.axios, this.basePath));
  }
}
