"""add-feature

Revision ID: e9a1eba6f06e
Revises:
Create Date: 2020-09-09 22:07:28.622072

"""
# pylint: skip-file
# flake8: noqa
# mypy: ignore-errors

import geoalchemy2
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "e9a1eba6f06e"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA mapt")
    op.create_table(
        "features",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("attributes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "geometry",
            geoalchemy2.types.Geometry(
                srid=3850, from_text="ST_GeomFromEWKT", name="geometry"
            ),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_features")),
        schema="mapt",
    )
    op.create_index(
        "ix_attributes",
        "features",
        ["attributes"],
        unique=False,
        schema="mapt",
        postgresql_using="gin",
    )
    op.create_index(
        op.f("ix_mapt_features_geometry"),
        "features",
        ["geometry"],
        unique=False,
        schema="mapt",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_mapt_features_geometry"), table_name="features", schema="mapt"
    )
    op.drop_index("ix_attributes", table_name="features", schema="mapt")
    op.drop_table("features", schema="mapt")
    op.execute("DROP SCHEMA mapt")
    # ### end Alembic commands ###
